@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Aug 14 10:41:40 +0800 2025
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto ba4bd07b7daa44108d225472a7c42449 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_dvb_s2x_256apsk_decoder_behav xil_defaultlib.tb_dvb_s2x_256apsk_decoder -log elaborate.log"
call xelab  -wto ba4bd07b7daa44108d225472a7c42449 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_dvb_s2x_256apsk_decoder_behav xil_defaultlib.tb_dvb_s2x_256apsk_decoder -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
